# Generated by Django 2.2 on 2019-05-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_ID',
        ),
        migrations.AlterField(
            model_name='article',
            name='auther_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='auther',
            name='fitst',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='auther',
            name='last',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='Discipline_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='number',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
