# Generated by Django 2.2 on 2019-05-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0003_auto_20190501_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auther',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='auther_ID',
            new_name='author_ID',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='auther_ID',
            new_name='author_ID',
        ),
        migrations.AddField(
            model_name='article',
            name='URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
