# Generated by Django 2.2 on 2019-05-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0010_article_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='month',
        ),
        migrations.RemoveField(
            model_name='article',
            name='year',
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
