# Generated by Django 2.2 on 2019-05-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0023_auto_20190527_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
