# Generated by Django 2.2 on 2019-06-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0026_remove_article_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
