# Generated by Django 2.2 on 2019-05-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0006_journal_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
