# Generated by Django 2.2 on 2019-05-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0007_journal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
