# Generated by Django 2.2 on 2019-05-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0008_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='Discipline',
            new_name='discipline',
        ),
        migrations.RenameField(
            model_name='discipline',
            old_name='Discipline_ID',
            new_name='discipline_ID',
        ),
        migrations.AddField(
            model_name='article',
            name='discipline',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='area',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='discipline',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
