# Generated by Django 2.2 on 2019-05-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0009_auto_20190523_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
