# Generated by Django 2.2 on 2019-05-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0014_auto_20190524_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_ID', models.IntegerField(blank=True, null=True)),
                ('board', models.IntegerField(blank=True, null=True)),
                ('discipline', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_ID', models.IntegerField(blank=True, null=True)),
                ('board_ID', models.IntegerField(blank=True, null=True)),
                ('person_ID', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('comment_div', models.IntegerField(blank=True, null=True)),
                ('good', models.IntegerField(blank=True, null=True)),
                ('reply', models.IntegerField(blank=True, null=True)),
                ('attach', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_ID', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('fitst', models.CharField(blank=True, max_length=128, null=True)),
                ('last', models.CharField(blank=True, max_length=128, null=True)),
                ('E_mail', models.IntegerField(blank=True, null=True)),
                ('my_site', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
