# Generated by Django 2.2 on 2019-05-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0015_board_comment_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='attach',
            new_name='attachment',
        ),
    ]
