# Generated by Django 2.2 on 2019-05-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0016_auto_20190524_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
