# Generated by Django 2.2 on 2019-05-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0019_auto_20190525_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='post',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
