# Generated by Django 2.2 on 2019-05-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0020_auto_20190525_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='C_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
