# Generated by Django 2.2 on 2019-05-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0022_auto_20190527_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
