# Generated by Django 2.2 on 2019-05-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0024_auto_20190530_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='document/%Y/%m/%d'),
        ),
    ]
