# Generated by Django 2.2 on 2019-06-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konchiwa', '0030_board_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='board',
        ),
    ]
